language: python # needed to get access to virtualenv
addons:
    postgresql: 9.2 # minimum supported postgres version
env:
    global:
        - TESTMODEL_URL=http://localhost:8080/intermine-demo
        - TESTMODEL_PATH=intermine-demo
    matrix:
        - TEST_SUITE=webapp # Long tests should be listed first, to make most of 
        - TEST_SUITE=bio    # concurrency
        - TEST_SUITE=ws CLIENT=JS
        - TEST_SUITE=ws CLIENT=PY
        - TEST_SUITE=all
        - TEST_SUITE=webtasks
        - TEST_SUITE=checkstyle
sudo: false # use container based infrastructure
jdk:
    - openjdk7
    - openjdk6
before_script:
    - ./config/travis/init.sh
before_install:
    - "export DISPLAY=:99.0"
    - ./config/travis/before-install.sh
script:
    - ./config/travis/run.sh
notifications:
  irc:
      channels:
          - "chat.freenode.net#intermine-ci"
      on_success: change
      on_error: change

