log_dir: "/tmp"
data_dir: "/micklem/data"

default_sources:
  - "BioGRID"
  - "FlyAnatomyOntology"
  - "FlyBaseFasta"
  - "FlyBaseOrthologues"
  - "FlyCVTerms"
  - "GOAnnotation"
  - "IntAct"
  - "IntActVocabulary"
  - "InterPro"
  - "InterProGO"
  - "MGIIdentifiers"
  - "NCBIGene"
  - "Panther"  
  - "PubMed"
  - "Reactome"
  - "RedFly"
  - "RGDIdentifiers"
  - "UniProt"
  - "WormIdentifiers"
  - "HomoloGene"
  - "OrthoDB"
  - "SGDIdentifiers"
  - "ZFINIdentifiers"
  - "MousePheno"
  - "HumanGeneIdentifiers"
  - "HPO"
  - "NCBIFasta"
  - "NCBIGff"
  - "ClinVar"
  - "IntActComplexes"
  - "HGNC"
  - "NCBIGeneHuman"
  - "Orphanet"

UniProt:
    organisms:
        - 3702
        - 6239
        - 7165
        - 7217
        - 7220
        - 7222
        - 7227
        - 7230
        - 7234
        - 7238
        - 7240
        - 7244
        - 7245
        - 7260
        - 7955
        - 9606
        - 10090
        - 10116
        - 46245
        - 559292
        - 6238
        - 31234
        - 135651
        - 281687
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 741158
        - 943925
        - 943926

